### ISSUE TITLE
asq from noob

### ISSUE THREAD

**Issue by NikiKaCode** [jabbany/StratuMITM#1]
> stratumitm@0.1.0 start /home/kadiyski/StratuMITM
> node server.js

/home/kadiyski/StratuMITM/lib/config/index.js:16
        throw new Error(
        ^

Error: Both file and fallback config files could not be read! SyntaxError: Unexpected string in JSON at position 447
    at ConfigReader.read (/home/kadiyski/StratuMITM/lib/config/index.js:16:15)
    at Object.<anonymous> (/home/kadiyski/StratuMITM/server.js:10:72)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stratumitm@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stratumitm@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kadiyski/.npm/_logs/2018-04-20T21_05_01_017Z-debug.log

and i don't know what must filled in this line of thee index.js
lib/config/index.js

**Comment by jabbany** [comment]
You need to create a config.json in the directory that you're running the command. There are samples of what it would look like in the docs.

There is no need to edit existing files but do nake sure that you also ran npm install after cloning the repo

**Comment by NikiKaCode** [comment]
@jabbany thank you for reply !
after clone i run in directory npm install , npm update ,
i edit
in docs dir  - UnifiedStatsServer.md - change only host + port ;
                              DebuggingServer.md - add some listen port , edit host+port;
 in config dir -         rewrite_credentials.sample.json - add wallet , edit host+port;
in main dir
config.sample.json - add wallet , edit host+port;

**Comment by NikiKaCode** [comment]
in lib/config/index.js 
is there something to edit in this file ?

var fs = require('fs');

var ConfigReader = (function () {
  var ConfigReader = function (defaults) {
    this._defaults = {};
  };
  
  ConfigReader.prototype.read = function (filename, fallback) {
    var config = {};
    try {
      config = JSON.parse(fs.readFileSync(filename));
    } catch (e) {
      try {
        config = JSON.parse(fs.readFileSync(fallback));
      } catch (e) {
        throw new Error(
          'Both file and fallback config files could not be read! ' + 
          e.toString());
      }
    }
    // Fill in anything that was not filled
    for (var key in this._defaults) {
      if (!key in config) {
        config[key] = this._defaults[key];
      }
    }
    return config;
  };

  return ConfigReader;
})();

exports.ConfigReader = ConfigReader;
exports.FALLBACK_CONFIG = {
  "ports": [6666],
  "logger": {
    "mode": "console",
    "params": {
      "color": true
    }
  },
  "rewriter": "./lib/rewrite/blackhole.js",
  "params": {
    "log": "all",
  }
};

**Comment by jabbany** [comment]
You shouldn't need to edit any js files. Instead you need to copy the json file from the docs with your changes and rename it as config.json. Then put it in the directory you're running the command to start the server.

**Comment by NikiKaCode** [comment]
ok .
I'll try :)

**Comment by NikiKaCode** [comment]
Hi @jabbany ,
i got it .
just in main dir must have both json files - config.json and config.sample.json . 
or edit line in server.js
..... Create the log var config = (new confreader.ConfigReader(confreader.FALLBACK_CONFIG)).read('config.json', 'config.sample.json')
