### ISSUE TITLE
100% share rejected

### ISSUE THREAD

**Issue by Canefis** [jabbany/StratuMITM#3]
Use of rewrite and change AgentID to my own, shares "submit" but never "accepted" and on the pool 100% rejected. Nicehash>>stratumitm>>pool.
Any ideas?

**Comment by b2d2dbone** [comment]
usually rejected shares due to low difficulty 

check nicehash end usually it requires high difficulty FOR EXAMPLE  SHA256  >= 500000.00 

or you can rent low difficulty rigs from miningrigrentals and confirm the issue 

good luck

**Comment by TheMaintainer** [comment]
usually rejected shares due to low difficulty

check nicehash end it requires high difficulty FOR EXAMPLE SHA256 >= 500000.00

or you can rent low difficulty rigs from miningrigrentals and confirm the issue

good luck
